In [1]:
import numpy as np
import pandas as pd
import torch

import sys, os
source_path = os.path.join(os.getcwd(), os.pardir, 'src')
sys.path.append(source_path)
source_path = os.path.join(os.getcwd(), os.pardir, 'preprocessing')
sys.path.append(source_path)
source_path = os.path.join(os.getcwd(), os.pardir, 'metrics')
sys.path.append(source_path)

from dl import GatedLinearUnit, GatedResidualNetwork

C:\Users\gilbe\anaconda3\envs\tokyo\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tgt = torch.tensor(np.array(range(10)) * 0.01)
feat = torch.tensor(np.array(range(100)) .reshape(10, 10), dtype=torch.float64).float()
print(feat.shape)
print(feat)
print(tgt.shape)
print(tgt)

print()
print('Network:')
units = 10
out_features = 1
glu = GatedLinearUnit(units=units).float()
print(glu(feat))

torch.Size([10, 10])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
        [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
        [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
        [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
        [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])
torch.Size([10])
tensor([0.0000, 0.0100, 0.0200, 0.0300, 0.0400, 0.0500, 0.0600, 0.0700, 0.0800,
        0.0900], dtype=torch.float64)

Network:
tensor([[-9.0402e+00,  1.5534e-03, -8.9204e+00, -6.9780e+00,  7.0781e-02,
          2.3727e-02, -9.5331e+00, -9.4034e+00,  3.6498e-02, -8.8722e+00],
        [-1.5556e+01,  8.7291e-04, -1.6132e+01, -7.0325e+00,  3.9689e-02,
          

C:\Users\gilbe\anaconda3\envs\tokyo\lib\site-packages\torch\nn\functional.py:1944: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [4]:
trained_model = torch.load('./trained_model.pt')
trained_model

NeuralNetwork(
  (embedding_layer): Embedding(2000, 300)
  (embedding_to_hidden): Linear(in_features=300, out_features=1024, bias=True)
  (embedding_output): Linear(in_features=1024, out_features=1, bias=True)
  (cont_input): Linear(in_features=4, out_features=1024, bias=True)
  (output_layer): Linear(in_features=1028, out_features=1, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
  (stacks): ModuleList(
    (0): NeuralStack(
      (stacks): ModuleList(
        (0): NeuralBlock(
          (dropout): Dropout(p=0.1, inplace=False)
          (layer1): Linear(in_features=1028, out_features=1028, bias=True)
          (layer2): Linear(in_features=1028, out_features=1028, bias=True)
          (layer3): Linear(in_features=1028, out_features=1028, bias=True)
          (layer4): Linear(in_features=1028, out_features=1028, bias=True)
          (output): Linear(in_features=1028, out_features=1028, bias=True)
          (res_output): Linear(in_features=1028, out_features=1028, bias=True)
    